### ISSUE TITLE
Error importing pycti library

### ISSUE THREAD

**Issue by mariodcosta** [OpenCTI-Platform/client-python#247]
Hey guys,

I am trying to **import pycti library** to use OpenCTIConnectorHelper, however it says that cannot find libmagic module.

I already explored a lot of solutions to install libmagic modules , however it doesn't work. Anyone got this problem using pycti library?

My OS is Windows 10 and I am using Visual Studio.

I attached the image.
![libmagic module](https://user-images.githubusercontent.com/13469672/159118405-d9ee097b-a980-48a3-a991-8156ab84480d.PNG)

**Comment by nor3th** [comment]
Hey

The correct libmagic library should be installed automatically.
https://github.com/OpenCTI-Platform/client-python/blob/master/requirements.txt#L4

Maybe remove all other libmagic modules and then try again?

Otherwise have a look at this: https://stackoverflow.com/questions/59661022/django-versatileimagefield-issues-no-matching-distribution-found-for-python-ma

Please let me know what worked in the end and if there are any adaptions needed concerning the requirements file.

Regards

**Comment by mariodcosta** [comment]
@nor3th thank you very much for your attention.

This solution worked for me [https://stackoverflow.com/a/59662952/13154961].

In resume , i added this command to the Dockerfile: "RUN apt-get update && apt-get install -y libmagic-dev"

**Comment by jonasjancarik** [comment]
On MacOS (Sonoma) it also seems to be necessary to install libmagic first on the system (e.g. `brew install libmagic`)
