### ISSUE TITLE
stix_cyber_observables.read() does not return all fields within the object

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/client-python#281]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

When querying OpenCTI for text based observables, such as `Text` or `Software` via pycti, not all observable fields are returned.

## Environment

1. OS (where OpenCTI server runs): AWS Linux 2
2. OpenCTI version: 5.3.9
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1 - Create/Verify that a Text/Software Observable is in the systems
2 - Query opencti for the Text/Software based observable

## Expected Output

return all fields

## Actual Output

Just the basic fields are returned.

## Additional information

<img width="1779" alt="Screen Shot 2022-09-26 at 10 44 04 AM" src="https://user-images.githubusercontent.com/30411037/192328466-f65c652d-0185-4091-9cf2-dfd8ecf147d4.png">
<img width="1245" alt="Screen Shot 2022-09-26 at 10 43 48 AM" src="https://user-images.githubusercontent.com/30411037/192328468-e90234cc-2220-42fd-b386-ea4c92b17cfd.png">

**Comment by SamuelHassine** [comment]
@TechBurn0ut: you have a "Text" observable with the value  Hacktool:Win32/Keygen and the returned value are correct.

Your query will never find the Observable "Software", because you're filtering on "value". And the software has the attribute in the field "name".

Please use the filter: 
```
{"key": "name", "values": ["Hacktool:Win32/Keygen"]}
```

And you will find your software. Please note that the "key" is the name of the attribute. Software observable type does not have any attribute named  "value".
